message(STATUS "====================================================")
message(STATUS "&&&    found executable programme: Chap4_1_StringADT")
add_executable(Chap4_1_StringADT Chap4_1_StringADT.cpp)
message(STATUS "&&&    found executable programme: Chap4_2_SString_PatternMatching")
add_executable(Chap4_2_SString_PatternMatching Chap4_2_SString_PatternMatching.cpp)
message(STATUS "&&&    found executable programme: Chap4_3_HString_PatternMatching")
add_executable(Chap4_3_HString_PatternMatching Chap4_3_HString_PatternMatching.cpp)
message(STATUS "&&&    found executable programme: Chap4_4_KMP")
add_executable(Chap4_4_KMP Chap4_4_KMP.cpp)
message(STATUS "***  Exiting Chapter folder Problems")
add_subdirectory(Problems)
