message(STATUS "====================================================")
message(STATUS "&&&    found executable programme: Q_Chap2_0_MindExpand")
add_executable(Q_Chap2_0_MindExpand Q_Chap2_0_MindExpand.cpp)
message(STATUS "&&&    found executable programme: Q_Chap2_1_Delete_minimum")
add_executable(Q_Chap2_1_Delete_minimum Q_Chap2_1_Delete_minimum.cpp)
message(STATUS "&&&    found executable programme: Q_Chap2_2_SequentialList_inverse")
add_executable(Q_Chap2_2_SequentialList_inverse Q_Chap2_2_SequentialList_inverse.cpp)
message(STATUS "&&&    found executable programme: Q_Chap2_3_DOUBLE_PTR_Delete_same_value")
add_executable(Q_Chap2_3_DOUBLE_PTR_Delete_same_value Q_Chap2_3_DOUBLE_PTR_Delete_same_value.cpp)
message(STATUS "&&&    found executable programme: Q_Chap2_4_DOUBLE_PTR_Delete_period")
add_executable(Q_Chap2_4_DOUBLE_PTR_Delete_period Q_Chap2_4_DOUBLE_PTR_Delete_period.cpp)
