message(STATUS "====================================================")
message(STATUS "&&&    found executable programme: Chap3_1_SequenceStack")
add_executable(Chap3_1_SequenceStack Chap3_1_SequenceStack.cpp)
message(STATUS "&&&    found executable programme: Chap3_2_SharedStack")
add_executable(Chap3_2_SharedStack Chap3_2_SharedStack.cpp)
message(STATUS "&&&    found executable programme: Chap3_3_LinkStack")
add_executable(Chap3_3_LinkStack Chap3_3_LinkStack.cpp)
message(STATUS "&&&    found executable programme: Chap3_4_SequenceQueue")
add_executable(Chap3_4_SequenceQueue Chap3_4_SequenceQueue.cpp)
message(STATUS "&&&    found executable programme: Chap3_5_CirculatedQueue")
add_executable(Chap3_5_CirculatedQueue Chap3_5_CirculatedQueue.cpp)
message(STATUS "&&&    found executable programme: Chap3_6_LinkQueue")
add_executable(Chap3_6_LinkQueue Chap3_6_LinkQueue.cpp)
message(STATUS "***  Exiting Chapter folder Problems")
add_subdirectory(Problems)
