message(STATUS "***  Exiting 2-level folder Chap1_DS")
add_subdirectory(Chap1_DS)
message(STATUS "***  Exiting 2-level folder Chap2_LinearList")
add_subdirectory(Chap2_LinearList)
message(STATUS "***  Exiting 2-level folder Chap3_StackQueue")
add_subdirectory(Chap3_StackQueue)
message(STATUS "***  Exiting 2-level folder Chap4_String")
add_subdirectory(Chap4_String)
message(STATUS "***  Exiting 2-level folder Chap5_Tree")
add_subdirectory(Chap5_Tree)
