message(STATUS "====================================================")
message(STATUS "&&&    found executable programme: 94.Binary_T_inorder_traversal(二叉树中序遍历)")
add_executable(94_Binary_T_inorder_traversal main.cpp)

message(STATUS "&&&    found executable programme: 94(*).Binary_T_preorder_traversal(二叉树前序遍历)")
add_executable(94A_Binary_T_preorder_traversal main2.cpp)

message(STATUS "&&&    found executable programme: 94(*).Binary_T_postorder_traversal(二叉树后序遍历)")
add_executable(94B_Binary_T_postorder_traversal main3.cpp)

message(STATUS "&&&    found executable programme: 94(*).Binary_T_table_traversal(二叉树表格法遍历)")
add_executable(94C_Binary_T_table_traversal table.cpp)


